export const PayloadFields = {
  Uuid: 'uuid',
  ContentType: 'content_type',
  ItemsKeyId: 'items_key_id',
  EncItemKey: 'enc_item_key',
  Content: 'content',
  CreatedAt: 'created_at',
  UpdatedAt: 'updated_at',
  Deleted: 'deleted',
  Legacy003AuthHash: 'auth_hash',
  Legacy003AuthParams: 'auth_params',
  Dirty: 'dirty',
  DirtiedDate: 'dirtiedDate',
  WaitingForKey: 'waitingForKey',
  ErrorDecrypting: 'errorDecrypting',
  ErrorDecryptingChanged: 'errorDecryptingValueChanged',
  Dummy: 'dummy',
  LastSyncBegan: 'lastSyncBegan',
  LastSyncEnd: 'lastSyncEnd'
};
