export const PAYLOAD_CONTENT_FORMAT_ENCRYPTED_STRING          = 0;
export const PAYLOAD_CONTENT_FORMAT_DECRYPTED_BARE_OBJECT     = 1;
export const PAYLOAD_CONTENT_FORMAT_DECRYPTED_BASE_64_STRING  = 2;
