export const APPLICATION_EVENT_WILL_SIGN_IN           = 'APPLICATION_EVENT_WILL_SIGN_IN';
export const APPLICATION_EVENT_DID_SIGN_IN            = 'APPLICATION_EVENT_DID_SIGN_IN';
export const APPLICATION_EVENT_DID_SIGN_OUT           = 'APPLICATION_EVENT_DID_SIGN_OUT';
export const APPLICATION_EVENT_DID_UNLOCK             = 'APPLICATION_EVENT_DID_UNLOCK';
