export const MAPPING_SOURCE_REMOTE_RETRIEVED          = 'MappingSourceRemoteRetrieved';
export const MAPPING_SOURCE_REMOTE_SAVED              = 'MappingSourceRemoteSaved';
export const MAPPING_SOURCE_LOCAL_SAVED               = 'MappingSourceLocalSaved';
export const MAPPING_SOURCE_LOCAL_RETRIEVED           = 'MappingSourceLocalRetrieved';
export const MAPPING_SOURCE_LOCAL_DIRTIED             = 'MappingSourceLocalDirtied';
export const MAPPING_SOURCE_COMPONENT_RETRIEVED       = 'MappingSourceComponentRetrieved';
export const MAPPING_SOURCE_DESKTOP_INSTALLED         = 'MappingSourceDesktopInstalled'; /** When a component is installed by the desktop and some of its values change */
export const MAPPING_SOURCE_REMOTE_ACTION_RETRIEVED   = 'MappingSourceRemoteActionRetrieved'; /** aciton-based Extensions like note history */
export const MAPPING_SOURCE_FILE_IMPORT               = 'MappingSourceFileImport';
