name: Git Sync

on:
  push:
    branches-ignore:
      - beta/*
      - master

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "standardnotes/snjs"
          source_branch: "refs/remotes/source/*"
          destination_repo: "standardnotes/private-snjs"
          destination_branch: "refs/heads/*"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
