name: Beta

on:
  push:
    branches: [ beta/* ]

jobs:
  lint:
    if: contains(github.event.head_commit.message, 'chore(release)') == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install --pure-lockfile
      - run: yarn build
      - run: yarn lint
  unit-tests:
    if: contains(github.event.head_commit.message, 'chore(release)') == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install --pure-lockfile
      - run: yarn build
      - run: yarn test:unit
  e2e-tests:
    if: contains(github.event.head_commit.message, 'chore(release)') == false
    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn test:e2e

  publish:
    needs: [lint, unit-tests, e2e-tests]
    if: contains(github.event.head_commit.message, 'chore(release)') == false

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Get beta branch name
        id: get_beta_name
        run: echo ::set-output name=beta_name::${GITHUB_REF/refs\/heads\/beta\//}
      - run: yarn install --pure-lockfile
      - run: yarn build
      - name: setup git config
        run: |
          git config --global user.name "standardci"
          git config --global user.email "ci@standardnotes.com"
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - run: yarn version-bump-beta --preid beta-${{ steps.get_beta_name.outputs.beta_name }}
      - run: yarn publish-packages-beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  git-sync:
    needs: publish

    runs-on: ubuntu-latest

    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "standardnotes/snjs"
          source_branch: "refs/remotes/source/*"
          destination_repo: "standardnotes/private-snjs"
          destination_branch: "refs/heads/*"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

  notify_discord:
    needs: publish
    if: contains(github.event.head_commit.message, 'chore(release)') == false

    runs-on: ubuntu-latest

    steps:
    - name: Run Discord Webhook
      uses: johnnyhuy/actions-discord-git-webhook@main
      with:
        webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
        censor_username: false
