name: Push to packages/decrypt

on:
  push:
    paths:
    - 'packages/decrypt/**'
    branches:
      - master

jobs:
  commit-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - run: yarn install --pure-lockfile
      - run: cd packages/decrypt
      - run: yarn build

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        with:
          file_pattern: dist/decrypt.html
          commit_message: "chore: build decrypt script"
          commit_user_name: "standardci"
          commit_user_email: "ci@standardnotes.com"
          commit_author: "standardci <ci@standardnotes.com>"
